org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
android.suppressUnsupportedCompileSdk=35
org.gradle.caching=true
org.gradle.parallel=true
kotlin.incremental=false
systemProp.org.gradle.internal.http.connection.timeout=120000
systemProp.org.gradle.internal.http.socket.timeout=120000
systemProp.org.gradle.internal.repository.max.retries=5
