// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0K_uXmml4DbgJE6PgKxiV4jYgNG2AuXo',
    appId: '1:586482140272:web:c60b43ef28d792af24a0b5',
    messagingSenderId: '586482140272',
    projectId: 'legash-fb879',
    authDomain: 'legash-fb879.firebaseapp.com',
    storageBucket: 'legash-fb879.firebasestorage.app',
    measurementId: 'G-PZ1JHNPQ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIlZJe6d9suIJyyU-0Ai3opACRycO8dI',
    appId: '1:586482140272:android:189e0299748d6ccc24a0b5',
    messagingSenderId: '586482140272',
    projectId: 'legash-fb879',
    storageBucket: 'legash-fb879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdvI5Zp2pInKCnP6jG49rLJGf0Re3k4Y',
    appId: '1:586482140272:ios:00acafea6bf54f5324a0b5',
    messagingSenderId: '586482140272',
    projectId: 'legash-fb879',
    storageBucket: 'legash-fb879.firebasestorage.app',
    iosClientId: '586482140272-khqhvgbu30vrotd9svmk81801dllmlda.apps.googleusercontent.com',
    iosBundleId: 'com.egash.egashMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdvI5Zp2pInKCnP6jG49rLJGf0Re3k4Y',
    appId: '1:586482140272:ios:00acafea6bf54f5324a0b5',
    messagingSenderId: '586482140272',
    projectId: 'legash-fb879',
    storageBucket: 'legash-fb879.firebasestorage.app',
    iosClientId: '586482140272-khqhvgbu30vrotd9svmk81801dllmlda.apps.googleusercontent.com',
    iosBundleId: 'com.egash.egashMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0K_uXmml4DbgJE6PgKxiV4jYgNG2AuXo',
    appId: '1:586482140272:web:3c1396f0caeec0b424a0b5',
    messagingSenderId: '586482140272',
    projectId: 'legash-fb879',
    authDomain: 'legash-fb879.firebaseapp.com',
    storageBucket: 'legash-fb879.firebasestorage.app',
    measurementId: 'G-CM0MCH5R8G',
  );
}
